services:
  db:
    image: mysql:8.0
    container_name: pos-db
    restart: always
    environment:
      MYSQL_DATABASE: pos_db
      MYSQL_USER: pos_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pos-network

  backend:
    build:
      context: ./POS-system-backend
      target: build
    container_name: pos-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    env_file:
      - .env
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pos_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: pos_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    volumes:
      - ./POS-system-backend:/app
    working_dir: /app
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - pos-network

  frontend:
    build:
      context: ./POS-system-frontend
      target: dev
    container_name: pos-frontend
    restart: always
    ports:
      - "3000:5173"
    volumes:
      - ./POS-system-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge

volumes:
  db_data:
